name: Suggestion
description: Suggest what can be improved or changed in the modpack.
title: "[Suggestion]: "
labels: ["suggestion"]
projects: []
body:
  - type: textarea
    id: suggestion
    attributes:
      label: Describe your suggestion
      description: What exactly do you want to suggest?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: By submitting this issue, you confirm that you are playing on the latest modpack version.
      options:
        - label: I confirm that I am playing on the latest version of the modpack.
          required: true
