name: Suggestion
description: Suggest what can be improved or changed in the modpack.
title: "[Suggestion]: "
labels: ["suggestion"]
projects: []
body:
  - type: textarea
    id: suggestion
    attributes:
      label: Describe your suggestion
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Describe your suggestion
      options:
        - label: I confirm that I am playing on the latest version of the modpack.
          required: true
